/*
  Generated by Generate_BlockingTrigger.vbs
  Generated: 07.08.2026 13:25:52
  Protected objects: 40
*/

if exists (
    select 1
    from sys.triggers
    where name = N'trg_Warn_ImportantObjects'
      and parent_class = 0
)
    drop trigger [trg_Warn_ImportantObjects] on database
go

create trigger [trg_Warn_ImportantObjects]
on database
for
    create_table,
    alter_table,
    drop_table,
    create_view,
    alter_view,
    drop_view,
    create_procedure,
    alter_procedure,
    drop_procedure,
    create_function,
    alter_function,
    drop_function
as
begin
    set nocount on

    declare @data xml = eventdata()
    declare @obj sysname = @data.value('(/EVENT_INSTANCE/ObjectName)[1]', 'sysname')
    declare @schema sysname = @data.value('(/EVENT_INSTANCE/SchemaName)[1]', 'sysname')

    if @obj in (
        -- Tables
        N'OperatorGroup',
        N'OperatorGroupItem',
        N'ProductionWorkSession',
        N'ScanHistory',
        N'UserGroupCatalogueRight',
        N'UserGroupPermission',
        N'UserGroupReportList',
        N'UserGroupRestrictColumn',
        N'UserGroups',
        -- Stored procedures
        N'sp_CreateSheduleOperator_IZO',
        N'sp_DepCalcReg_Add_Group',
        N'sp_GetMaterialsWithDateGap',
        N'sp_GetPendingDepTrans',
        N'sp_GetRest_AllDepList',
        N'sp_GetRest_DepTurnDepList',
        N'sp_GetRest_DepTurnDepList_0_2',
        N'sp_GetTaskTreeLogistic',
        N'sp_Invoice_IZO_Ship_Only',
        N'sp_RTB_ProjectCopy',
        N'sp_TTN_Task_MXG_Multi',
        N'sp_UPD_Task_XLS_Izolux_Export',
        -- Functions
        N'f_GetNextAccountNum_BW',
        N'f_SawTaskUE_Period_Detail_Shipment',
        N'f_SawTaskUE_Period_Operator_Shipment',
        -- Views
        N'v_Invoice_MXG',
        N'v_Invoice_Reject_IZO',
        N'v_InvoiceUKD',
        N'v_ManagerReport',
        N'v_OperatorBrigadierMap',
        N'v_Report_GlassWasteBySawTask',
        N'v_SawItemSelect_Task',
        N'v_SawTask_Statistics',
        N'v_SawTaskUE_Period_Detail_Assembly_IZO',
        N'v_SawTaskUE_Period_Detail_Cut_IZO',
        N'v_SawTaskUE_Period_Detail_ZAK_IZO',
        N'v_SawTaskUE_Period_Operator_Assembly_IZO',
        N'v_SawTaskUE_Period_Operator_Cut_IZO',
        N'v_SawTaskUE_Period_Operator_ZAK_IZO',
        N'v_Volume_Money_SubDivision',
        N'w_Invoice_4_IZO'
    )
    begin
        declare @message nvarchar(2048)
        set @message = N'Modification of protected object is blocked: ' +
            quotename(coalesce(@schema, N'')) + N'.' + quotename(coalesce(@obj, N''))

        raiserror(N'%s', 16, 1, @message)
        rollback transaction
    end
end
go
