Option Explicit

' Generates a database DDL trigger from SQL object definitions located in:
'   ..\Tables, ..\SP, ..\Function and ..\View
' The generated SQL file is placed next to this script.

Const ForReading = 1
Const TristateUseDefault = -2

Dim fso, scriptDir, sqlRoot, outputPath, triggerName
Set fso = CreateObject("Scripting.FileSystemObject")

scriptDir = fso.GetParentFolderName(WScript.ScriptFullName)
sqlRoot = fso.GetParentFolderName(scriptDir)
outputPath = fso.BuildPath(scriptDir, "Auto_Block_Changes.sql")
triggerName = "trg_Warn_ImportantObjects"

Dim tables, procedures, functions, views
Set tables = NewDictionary()
Set procedures = NewDictionary()
Set functions = NewDictionary()
Set views = NewDictionary()

CollectObjects fso.BuildPath(sqlRoot, "Tables"), Array("table"), tables
CollectObjects fso.BuildPath(sqlRoot, "SP"), Array("procedure", "proc"), procedures
CollectObjects fso.BuildPath(sqlRoot, "Function"), Array("function"), functions
CollectObjects fso.BuildPath(sqlRoot, "View"), Array("view"), views

Dim totalCount
totalCount = tables.Count + procedures.Count + functions.Count + views.Count

If totalCount = 0 Then
  Fail "No SQL objects were found."
End If

WriteTrigger outputPath, triggerName, tables, procedures, functions, views

WScript.Echo "OK: generated " & outputPath
WScript.Echo "Tables: " & tables.Count
WScript.Echo "Stored procedures: " & procedures.Count
WScript.Echo "Functions: " & functions.Count
WScript.Echo "Views: " & views.Count
WScript.Echo "Total protected objects: " & totalCount
WScript.Quit 0

Function NewDictionary()
  Dim dict
  Set dict = CreateObject("Scripting.Dictionary")
  dict.CompareMode = 1 ' TextCompare
  Set NewDictionary = dict
End Function

Sub CollectObjects(ByVal folderPath, ByVal keywords, ByRef objects)
  Dim folder, file, subFolder

  If Not fso.FolderExists(folderPath) Then
    Fail "Folder not found: " & folderPath
  End If

  Set folder = fso.GetFolder(folderPath)

  For Each file In folder.Files
    If LCase(fso.GetExtensionName(file.Name)) = "sql" Then
      ScanSqlFile file.Path, keywords, objects
    End If
  Next

  For Each subFolder In folder.SubFolders
    CollectObjects subFolder.Path, keywords, objects
  Next
End Sub

Sub ScanSqlFile(ByVal filePath, ByVal keywords, ByRef objects)
  Dim input, sqlText, keyword, re, matches, match, rawName, objectName

  Set input = fso.OpenTextFile(filePath, ForReading, False, TristateUseDefault)
  sqlText = input.ReadAll
  input.Close

  For Each keyword In keywords
    Set re = New RegExp
    re.Pattern = "^\s*create\s+(or\s+alter\s+)?" & keyword & _
      "\s+((\[[^]]+\]|[A-Za-z0-9_@$#]+)(\s*\.\s*(\[[^]]+\]|[A-Za-z0-9_@$#]+))?)"
    re.IgnoreCase = True
    re.Global = True
    re.MultiLine = True

    Set matches = re.Execute(sqlText)
    For Each match In matches
      rawName = CStr(match.SubMatches(1))
      objectName = NormalizeObjectName(rawName)

      If Len(objectName) > 0 Then
        If Left(objectName, 1) <> "#" Then
          If Not objects.Exists(objectName) Then
            objects.Add objectName, filePath
          End If
        End If
      End If
    Next
  Next
End Sub

Function NormalizeObjectName(ByVal rawName)
  Dim value, dotPosition

  value = Replace(rawName, " ", "")
  value = Replace(value, vbTab, "")
  value = Replace(value, vbCr, "")
  value = Replace(value, vbLf, "")

  dotPosition = InStrRev(value, ".")
  If dotPosition > 0 Then
    value = Mid(value, dotPosition + 1)
  End If

  If Len(value) >= 2 Then
    If Left(value, 1) = "[" And Right(value, 1) = "]" Then
      value = Mid(value, 2, Len(value) - 2)
      value = Replace(value, "]]", "]")
    End If
  End If

  NormalizeObjectName = value
End Function

Sub WriteTrigger(ByVal filePath, ByVal ddlTriggerName, ByRef tableObjects, ByRef procedureObjects, ByRef functionObjects, ByRef viewObjects)
  Dim out, total, written

  total = tableObjects.Count + procedureObjects.Count + functionObjects.Count + viewObjects.Count
  written = 0

  Set out = fso.CreateTextFile(filePath, True, False) ' ANSI

  out.WriteLine "/*"
  out.WriteLine "  Generated by Generate_BlockingTrigger.vbs"
  out.WriteLine "  Generated: " & Now
  out.WriteLine "  Protected objects: " & total
  out.WriteLine "*/"
  out.WriteLine ""
  out.WriteLine "if exists ("
  out.WriteLine "    select 1"
  out.WriteLine "    from sys.triggers"
  out.WriteLine "    where name = N'" & EscapeSqlText(ddlTriggerName) & "'"
  out.WriteLine "      and parent_class = 0"
  out.WriteLine ")"
  out.WriteLine "    drop trigger [" & EscapeSqlIdentifier(ddlTriggerName) & "] on database"
  out.WriteLine "go"
  out.WriteLine ""
  out.WriteLine "create trigger [" & EscapeSqlIdentifier(ddlTriggerName) & "]"
  out.WriteLine "on database"
  out.WriteLine "for"
  out.WriteLine "    create_table,"
  out.WriteLine "    alter_table,"
  out.WriteLine "    drop_table,"
  out.WriteLine "    create_view,"
  out.WriteLine "    alter_view,"
  out.WriteLine "    drop_view,"
  out.WriteLine "    create_procedure,"
  out.WriteLine "    alter_procedure,"
  out.WriteLine "    drop_procedure,"
  out.WriteLine "    create_function,"
  out.WriteLine "    alter_function,"
  out.WriteLine "    drop_function"
  out.WriteLine "as"
  out.WriteLine "begin"
  out.WriteLine "    set nocount on"
  out.WriteLine ""
  out.WriteLine "    declare @data xml = eventdata()"
  out.WriteLine "    declare @obj sysname = @data.value('(/EVENT_INSTANCE/ObjectName)[1]', 'sysname')"
  out.WriteLine "    declare @schema sysname = @data.value('(/EVENT_INSTANCE/SchemaName)[1]', 'sysname')"
  out.WriteLine ""
  out.WriteLine "    if @obj in ("

  WriteCategory out, "Tables", tableObjects, written, total
  WriteCategory out, "Stored procedures", procedureObjects, written, total
  WriteCategory out, "Functions", functionObjects, written, total
  WriteCategory out, "Views", viewObjects, written, total

  out.WriteLine "    )"
  out.WriteLine "    begin"
  out.WriteLine "        declare @message nvarchar(2048)"
  out.WriteLine "        set @message = N'Modification of protected object is blocked: ' +"
  out.WriteLine "            quotename(coalesce(@schema, N'')) + N'.' + quotename(coalesce(@obj, N''))"
  out.WriteLine ""
  out.WriteLine "        raiserror(N'%s', 16, 1, @message)"
  out.WriteLine "        rollback transaction"
  out.WriteLine "    end"
  out.WriteLine "end"
  out.WriteLine "go"

  out.Close
End Sub

Sub WriteCategory(ByRef out, ByVal title, ByRef objects, ByRef written, ByVal total)
  Dim keys, i, suffix
  Set keys = SortedKeys(objects)

  If keys.Count = 0 Then Exit Sub

  out.WriteLine "        -- " & title

  For i = 0 To keys.Count - 1
    written = written + 1
    suffix = ","
    If written = total Then suffix = ""

    out.WriteLine "        N'" & EscapeSqlText(CStr(keys(i))) & "'" & suffix
  Next
End Sub

Function SortedKeys(ByRef objects)
  Dim list, key
  Set list = CreateObject("System.Collections.ArrayList")

  For Each key In objects.Keys
    list.Add CStr(key)
  Next

  list.Sort
  Set SortedKeys = list
End Function

Function EscapeSqlText(ByVal value)
  EscapeSqlText = Replace(value, "'", "''")
End Function

Function EscapeSqlIdentifier(ByVal value)
  EscapeSqlIdentifier = Replace(value, "]", "]]" )
End Function

Sub Fail(ByVal message)
  WScript.Echo "ERROR: " & message
  WScript.Quit 1
End Sub
